version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && export SECRET_KEY_BASE=`bundle exec rake secret` && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/pop
    ports:
      - "3000:3000"
    depends_on:
      - db
