title: People on Projects
author: Hootsuite
description: > # this means to ignore newlines until "baseurl:"
  PoP

baseurl: "/pop/" # the subpath of your site, e.g. /blog/
url: "https://hootsuite.github.io"
github_username:  hootsuite/pop

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
